// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CRUDExampleBoardTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cRUDExampleBoard() {
    driver.get("https://trello.com/cyprianczerwinski/boards");
    driver.manage().window().setSize(new Dimension(974, 672));
    driver.findElement(By.cssSelector(".boards-page-board-section:nth-child(4) p > span")).click();
    driver.findElement(By.cssSelector(".nch-textfield__input")).sendKeys("testowa tablica");
    driver.findElement(By.cssSelector(".nch-textfield__input")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.name("name")).sendKeys("testowa lista");
    driver.findElement(By.name("name")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".mod-show-menu > .icon-sm")).click();
    driver.findElement(By.linkText("Więcej")).click();
    driver.findElement(By.linkText("Zamknij tablicę...")).click();
    driver.findElement(By.cssSelector(".js-confirm")).click();
    driver.findElement(By.cssSelector(".\\_3ZZkvSn-U9BxDK")).click();
    driver.findElement(By.cssSelector(".\\_4rSLRU_itQllPh")).click();
  }
}
